// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'card': string;
  'card__image': string;
  'card__name': string;
  'draw-border': string;
  'grid-container': string;
  'profile_card': string;
  'social-icons': string;
}
export const cssExports: CssExports;
export default cssExports;
