query getAllMode($accessKey: String = "", $input: CreateModeInput = {}) {
  getAllMode(accessKey: $accessKey, input: $input) {
    description
    id
    status
    title
    type
  }
}

query getMode($accessKey: String = "", $id: String = "") {
  getMode(accessKey: $accessKey, id: $id) {
    id
    title
    status
    type
  }
}

mutation createMode($accessKey: String = "", $input: CreateModeInput = {}) {
  createMode(accessKey: $accessKey, input: $input) {
    id
  }
}

mutation updateMode($accessKey: String = "", $input: CreateModeInput = {}) {
  updateMode(accessKey: $accessKey, input: $input) {
    id
  }
}

query getAllActiveMode($accessKey: String = "") {
  getAllActiveMode(accessKey: $accessKey) {
    id
    title
    type
    description
  }
}
