query posts($options: PageQueryOptions) {
  posts(options: $options) {
    data {
      id
      title
    }
    meta {
      totalCount
    }
  }
}

mutation updatePost($input: UpdatePostInput!, $id: ID!) {
  updatePost(input: $input, id: $id) {
    id
  }
}

mutation createPost($body: String = "", $title: String = "") {
  createPost(input: { title: $title, body: $body }) {
    id
  }
}

mutation deletePost($id: ID!) {
  deletePost(id: $id)
}
