query getJobs($filter: JobFilter = {}) {
  getJobs(filter: $filter) {
    metadata {
      limit
      page
      total
    }
    records {
      grossSalary
      id
      status
      title
    }
  }
}

mutation deleteJobs($id: String = "") {
  deleteJob(id: $id)
}

mutation createJob($input: JobInput!) {
  createJob(input: $input) {
    grossSalary
    id
    status
    title
  }
}

mutation updateJobs($input: JobUpdate = { id: "" }) {
  updateJob(input: $input)
}
