export declare const Regex: {
    IdCard: RegExp;
    plate: RegExp;
    bdV9: RegExp;
    positiveInteger: RegExp;
    companyCode: RegExp;
    fax: RegExp;
    qq: RegExp;
    bankNo: RegExp;
    number: RegExp;
    decimal2: RegExp;
    unEmpty: RegExp;
    username: RegExp;
    password: RegExp;
    mobPhone: RegExp;
    captcha: RegExp;
    smsVerify: RegExp;
    telPhone: RegExp;
    phone: RegExp;
    phoneCode: RegExp;
    personCode: RegExp;
    bankCard: RegExp;
    integer: RegExp;
    email: RegExp;
    url: RegExp;
    httpUrl: RegExp;
};
